# Part of OmaSettings. Sourced by bin/omasettings; not run on its own.

# ------------------------------------------------------- Hyprland plumbing

# Every Hyprland setting the window can touch: our key, the Hyprland keyword,
# and the value type used to read it back out of `hyprctl getoption`.
hypr_keyword() {
  case $1 in
    gaps-in) echo "general:gaps_in css" ;;
    gaps-out) echo "general:gaps_out css" ;;
    border-size) echo "general:border_size int" ;;
    rounding) echo "decoration:rounding int" ;;
    active-opacity) echo "decoration:active_opacity float" ;;
    inactive-opacity) echo "decoration:inactive_opacity float" ;;
    dim-inactive) echo "decoration:dim_inactive bool" ;;
    dim-strength) echo "decoration:dim_strength float" ;;
    blur) echo "decoration:blur:enabled bool" ;;
    blur-size) echo "decoration:blur:size int" ;;
    blur-passes) echo "decoration:blur:passes int" ;;
    animations) echo "animations:enabled bool" ;;
    kb-layout) echo "input:kb_layout str" ;;
    kb-variant) echo "input:kb_variant str" ;;
    kb-options) echo "input:kb_options str" ;;
    repeat-rate) echo "input:repeat_rate int" ;;
    repeat-delay) echo "input:repeat_delay int" ;;
    numlock) echo "input:numlock_by_default bool" ;;
    sensitivity) echo "input:sensitivity float" ;;
    accel-profile) echo "input:accel_profile str" ;;
    follow-mouse) echo "input:follow_mouse int" ;;
    natural-scroll) echo "input:touchpad:natural_scroll bool" ;;
    disable-while-typing) echo "input:touchpad:disable_while_typing bool" ;;
    clickfinger) echo "input:touchpad:clickfinger_behavior bool" ;;
    tap-to-click) echo "input:touchpad:tap-to-click bool" ;;
    scroll-factor) echo "input:touchpad:scroll_factor float" ;;
    *) return 1 ;;
  esac
}

# The live value, straight from the compositor — authoritative regardless of
# which file (ours, theirs, a theme's) last set it.
hypr_read() {
  local key=$1 spec keyword type raw
  spec=$(hypr_keyword "$key") || return 1
  keyword=${spec%% *}
  type=${spec##* }
  raw=$(hyprctl -j getoption "$keyword" 2>/dev/null) || return 1
  [[ -n $raw ]] || return 1
  case $type in
    int) jq -c '(.int // 0)' <<<"$raw" ;;
    # Gaps come back as a CSS-style "2 2 2 2" box rather than an int; the
    # window edits them as one number, so read the first side.
    css) jq -c '((.css // "0") | split(" ") | .[0] | tonumber? // 0)' <<<"$raw" ;;
    float) jq -c '((.float // 0) * 1000 | round) / 1000' <<<"$raw" ;;
    bool) jq -c '((.int // 0) != 0)' <<<"$raw" ;;
    # Hyprland spells "no value set" as [[EMPTY]]; the window wants "".
    str) jq -c '((.str // "") | if . == "[[EMPTY]]" then "" else . end)' <<<"$raw" ;;
  esac
}

hypr_state() {
  local out='{}' key value
  for key in gaps-in gaps-out border-size rounding active-opacity inactive-opacity \
             dim-inactive dim-strength blur blur-size blur-passes animations \
             kb-layout kb-variant kb-options repeat-rate repeat-delay numlock \
             sensitivity accel-profile follow-mouse natural-scroll \
             disable-while-typing clickfinger tap-to-click scroll-factor; do
    value=$(hypr_read "$key") || continue
    out=$(jq -c --arg k "$key" --argjson v "$value" '.[$k] = $v' <<<"$out")
  done
  echo "$out"
}

lua_value() {
  local value=$1
  case $value in
    true|false) echo "$value" ;;
    ''|*[!0-9.-]*) printf '"%s"' "$value" ;;
    *) echo "$value" ;;
  esac
}

# Render the store into a generated Lua file (or a conf file on pre-Lua
# setups), and make sure the user's top-level config loads it.
render_managed() {
  local store keys
  store=$(read_store)

  if [[ -f $HYPR_DIR/hyprland.lua ]]; then
    render_managed_lua "$store"
    ensure_loaded "$HYPR_DIR/hyprland.lua" 'require("hypr.omasettings")'
  else
    render_managed_conf "$store"
    ensure_loaded "$HYPR_DIR/hyprland.conf" 'source = ~/.config/hypr/omasettings.conf'
  fi
}

render_managed_lua() {
  local store=$1 pairs

  # Each stored key knows its Hyprland keyword path (e.g. input:touchpad:
  # natural_scroll); jq then folds those paths back into the nested tables the
  # Lua config expects, so two touchpad settings share one touchpad table
  # instead of overwriting each other.
  pairs=$(while read -r key; do
    spec=$(hypr_keyword "$key") || continue
    jq -cn --arg key "$key" --arg keyword "${spec%% *}" '{key: $key, path: ($keyword | split(":"))}'
  done < <(jq -r '.hypr // {} | keys[]' <<<"$store") | jq -s -c .)

  {
    echo "-- Generated by OmaSettings ($MANAGED_MARKER) — do not edit by hand."
    echo "-- Every value here was set from the OmaSettings window; delete a line"
    echo "-- to hand that setting back to your own config."
    echo ""
    jq -r --argjson pairs "$pairs" '
      def lua(v):
        if v == true or v == false then (v | tostring)
        elif (v | type) == "number" then (v | tostring)
        else "\"" + (v | tostring) + "\"" end;
      def render(obj; indent):
        [obj | to_entries[]
          | if (.value | type) == "object"
            then indent + .key + " = {\n" + render(.value; indent + "  ") + indent + "},\n"
            else indent + .key + " = " + lua(.value) + ",\n" end]
        | join("");
      . as $store
      | reduce $pairs[] as $p ({}; setpath($p.path; $store.hypr[$p.key]))
      | to_entries[]
      | "hl.config({\n  " + .key + " = {\n" + render(.value; "    ") + "  },\n})\n"
    ' <<<"$store"
  } | write_file "$MANAGED_LUA" managed
}

render_managed_conf() {
  local store=$1 body="" keyword value
  while read -r key; do
    spec=$(hypr_keyword "$key") || continue
    keyword=${spec%% *}
    value=$(jq -r --arg k "$key" '.hypr[$k]' <<<"$store")
    body+="$(tr ':' ':' <<<"$keyword") = $value"$'\n'
  done < <(jq -r '.hypr // {} | keys[]' <<<"$store")

  {
    echo "# Generated by OmaSettings ($MANAGED_MARKER) — do not edit by hand."
    echo ""
    printf "%s" "$body"
  } | write_file "$MANAGED_CONF" managed
}

# Append the load line to the user's top-level config exactly once.
ensure_loaded() {
  local file=$1 line=$2
  [[ -f $file ]] || return 0
  grep -qF "$line" "$file" && return 0
  backup_once "$file"
  {
    echo ""
    echo "-- Load settings written by OmaSettings ($MANAGED_MARKER)."
    echo "$line"
  } >>"$file"
}

hypr_set() {
  local key=$1 value=$2 spec keyword type
  spec=$(hypr_keyword "$key") || return 1
  keyword=${spec%% *}
  type=${spec##* }

  case $type in
    int|css) [[ $value =~ ^-?[0-9]+$ ]] || die "'$value' is not a whole number" ;;
    float) [[ $value =~ ^-?[0-9]+(\.[0-9]+)?$ ]] || die "'$value' is not a number" ;;
    bool) [[ $value == true || $value == false ]] || die "'$value' is not true or false" ;;
  esac

  local applied=$value
  [[ $type == bool ]] && { [[ $value == true ]] && applied=1 || applied=0; }
  hyprctl keyword "$keyword" "$applied" >/dev/null 2>&1

  local json
  if [[ $type == bool ]]; then json=$value
  elif [[ $type == str ]]; then json=$(jq -Rn --arg v "$value" '$v')
  else json=$value
  fi
  edit_store '.hypr = ((.hypr // {}) | .[$key] = $value)' --arg key "$key" --argjson value "$json"
}
