# Part of OmaSettings. Sourced by bin/omasettings; not run on its own.

# ----------------------------------------------------------------------- wifi

# NetworkManager is the authority here; nothing about wireless is stored or
# generated by OmaSettings. `-t` output escapes colons inside values, so every
# read unescapes rather than splitting naively.
wifi_device() {
  capture nmcli -t -f DEVICE,TYPE,STATE dev status \
    | awk -F: '$2 == "wifi" { print $1; exit }'
}

wifi_saved() {
  capture nmcli -t -f NAME,TYPE con show \
    | awk -F: '$NF ~ /wireless/ { name = $0; sub(/:[^:]*$/, "", name); print name }'
}

# Access points, strongest first, one row per network rather than one per
# radio: the same network seen from three access points is still one choice.
wifi_networks() {
  local saved
  saved=$(wifi_saved | jq -R -s -c 'split("\n") | map(select(length > 0))')

  capture nmcli -t -f IN-USE,SSID,SIGNAL,SECURITY dev wifi list --rescan no \
    | awk '
      {
        # Unescape "\:" so an SSID containing a colon survives the split.
        n = 0
        field = ""
        delete fields
        for (i = 1; i <= length($0); i++) {
          c = substr($0, i, 1)
          if (c == "\\") { i++; field = field substr($0, i, 1); continue }
          if (c == ":") { fields[++n] = field; field = ""; continue }
          field = field c
        }
        fields[++n] = field
        if (fields[2] == "") next
        printf "%s\t%s\t%s\t%s\n", (fields[1] == "*" ? "true" : "false"), fields[2], fields[3], fields[4]
      }
    ' \
    | jq -R -s -c --argjson saved "${saved:-[]}" 'split("\n")
      | map(select(length > 0) | split("\t") | . as $row
        | { ssid: $row[1],
            active: ($row[0] == "true"),
            signal: ($row[2] | tonumber? // 0),
            security: $row[3],
            secured: ($row[3] != "" and $row[3] != "--"),
            # Inside the pipe `.` is $saved, so the ssid is bound first —
            # otherwise index() would test $saved against itself.
            saved: (($saved | index($row[1])) != null) })
      | group_by(.ssid)
      | map(reduce .[] as $ap (.[0]; if $ap.signal > .signal then $ap + { active: (.active or $ap.active) } else . + { active: (.active or $ap.active) } end))
      | sort_by(-(if .active then 1000 else 0 end) - .signal)'
}

# Address, gateway and resolvers as the Wi-Fi device itself has them. The
# default route is not a reliable source here: with a VPN up it points at the
# tunnel, which is not the answer to "what is my address on this network".
wifi_connection() {
  local device=$1
  [[ -n $device ]] || { echo '{}'; return; }

  capture nmcli -t -f IP4.ADDRESS,IP4.GATEWAY,IP4.DNS dev show "$device" \
    | jq -R -s -c 'split("\n")
      | map(select(length > 0) | (index(":") // -1) as $at
        | select($at > 0) | { key: .[0:$at], value: .[$at + 1:] })
      | from_entries
      | { ip: ((.["IP4.ADDRESS[1]"] // "") | sub("/.*$"; "")),
          prefix: ((.["IP4.ADDRESS[1]"] // "") | capture("/(?<p>[0-9]+)$").p? // ""),
          gateway: (.["IP4.GATEWAY"] // ""),
          dns: ([.["IP4.DNS[1]"], .["IP4.DNS[2]"]] | map(select(. != null and . != ""))) }'
}

# The same band control the bar's network widget offers: pin 2.4, 5 or 6 GHz,
# or leave it automatic and let the radio choose.
wifi_band() {
  local report
  report=$(capture omarchy-network-band) || { echo '{}'; return; }
  jq -R -s -c 'split("\n")
    | map(select(length > 0) | split("\t"))
    | map({ key: .[0], value: (.[1] // "") })
    | from_entries
    | { current: (.band // ""),
        selected: (.selected // "auto"),
        available: ((.available // "") | split(" ") | map(select(length > 0))) }' <<<"$report"
}

wifi_state() {
  local enabled device networks connection band
  enabled=$(capture nmcli -t -f WIFI general status | head -n1)
  device=$(wifi_device)
  networks=$([[ $enabled == enabled ]] && wifi_networks || echo '[]')
  connection=$(wifi_connection "$device")
  band=$(wifi_band)

  jq -cn --argjson available "$(command -v nmcli >/dev/null 2>&1 && echo true || echo false)" \
    --argjson enabled "$([[ $enabled == enabled ]] && echo true || echo false)" \
    --arg device "${device:-}" \
    --argjson networks "${networks:-[]}" \
    --argjson connection "${connection:-{\}}" \
    --argjson band "${band:-{\}}" \
    '{ available: $available, enabled: $enabled, device: $device, networks: $networks,
       connection: $connection, band: $band,
       connected: (($networks[] | select(.active) | .ssid) // "") }'
}

wifi_cmd() {
  local action=${1:-} ssid=${2:-} password=${3:-}
  command -v nmcli >/dev/null 2>&1 || die "NetworkManager is not available"

  case $action in
    list) wifi_state ;;
    rescan)
      nmcli dev wifi rescan >/dev/null 2>&1 || true
      # A scan takes a moment to land; without the pause the list that comes
      # back is the one we already had.
      sleep 2
      wifi_state ;;
    poll)
      # For the page's own refresh loop: ask for a scan and return what is
      # known right now, without waiting for it. NetworkManager rate-limits
      # rescans and answers the request with an error when one came too soon,
      # which is fine — the next poll picks up whatever that scan found.
      nmcli dev wifi rescan >/dev/null 2>&1 || true
      wifi_state ;;
    radio)
      case $ssid in
        on|off) nmcli radio wifi "$ssid" >/dev/null 2>&1 || die "could not turn Wi-Fi $ssid" ;;
        *) die "expected on or off" ;;
      esac ;;
    connect)
      [[ -n $ssid ]] || die "no network given"
      local output
      if [[ -n $password ]]; then
        # --ask reads the passphrase from stdin, so it never appears in the
        # process list the way `nmcli ... password <secret>` would.
        output=$(printf '%s\n' "$password" | timeout 45 nmcli --ask dev wifi connect "$ssid" 2>&1)
      elif wifi_saved | grep -qxF "$ssid"; then
        output=$(timeout 45 nmcli con up id "$ssid" 2>&1)
      else
        output=$(timeout 45 nmcli dev wifi connect "$ssid" 2>&1)
      fi
      grep -qiE '^error|failed' <<<"$output" && die "${output#Error: }"
      true ;;
    band)
      case $ssid in
        auto|2.4|5|6) omarchy-network-band "$ssid" >/dev/null 2>&1 || die "could not pin the band to $ssid" ;;
        *) die "expected auto, 2.4, 5 or 6" ;;
      esac ;;
    disconnect)
      local device
      device=$(wifi_device)
      [[ -n $device ]] || die "no Wi-Fi device"
      nmcli dev disconnect "$device" >/dev/null 2>&1 || die "could not disconnect" ;;
    forget)
      [[ -n $ssid ]] || die "no network given"
      nmcli con delete id "$ssid" >/dev/null 2>&1 || die "no saved network called '$ssid'" ;;
    *) die "unknown wifi action '$action'" ;;
  esac
}
